config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :user_rewards
  resources :user_projects
  resources :project_categories
  resources :rewards
  resources :payments
  resources :projects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
  before_action :set_user_project, only: [:show, :edit, :update, :destroy]

  # GET /user_projects
  # GET /user_projects.json
  def index
    @user_projects = UserProject.all
  end

  # GET /user_projects/1
  # GET /user_projects/1.json
  def show
  end

  # GET /user_projects/new
  def new
    @user_project = UserProject.new
  end

  # GET /user_projects/1/edit
  def edit
  end

  # POST /user_projects
  # POST /user_projects.json
  def create
    @user_project = UserProject.new(user_project_params)

    respond_to do |format|
      if @user_project.save
        format.html { redirect_to @user_project, notice: 'User project was successfully created.' }
        format.json { render :show, status: :created, location: @user_project }
      else
        format.html { render :new }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_projects/1
  # PATCH/PUT /user_projects/1.json
  def update
    respond_to do |format|
      if @user_project.update(user_project_params)
        format.html { redirect_to @user_project, notice: 'User project was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_project }
      else
        format.html { render :edit }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_projects/1
  # DELETE /user_projects/1.json
  def destroy
    @user_project.destroy
    respond_to do |format|
      format.html { redirect_to user_projects_url, notice: 'User project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_project
      @user_project = UserProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_project_params
      params.require(:user_project).permit(:user_id, :project_id)
    end
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/views/user_projects/_form.html.erb
<%= form_with(model: user_project, local: true) do |form| %>
  <% if user_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_project.errors.count, "error") %> prohibited this user_project from being saved:</h2>

      <ul>
      <% user_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_project_user_id %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, id: :user_project_project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_projects/edit.html.erb
<h1>Editing User Project</h1>

<%= render 'form', user_project: @user_project %>

<%= link_to 'Show', @user_project %> |
<%= link_to 'Back', user_projects_path %>

app/views/user_projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Projects</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_projects.each do |user_project| %>
      <tr>
        <td><%= user_project.user %></td>
        <td><%= user_project.project %></td>
        <td><%= link_to 'Show', user_project %></td>
        <td><%= link_to 'Edit', edit_user_project_path(user_project) %></td>
        <td><%= link_to 'Destroy', user_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Project', new_user_project_path %>

app/views/user_projects/new.html.erb
<h1>New User Project</h1>

<%= render 'form', user_project: @user_project %>

<%= link_to 'Back', user_projects_path %>

app/views/user_projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_project.user %>
</p>

<p>
  <strong>Project:</strong>
  <%= @user_project.project %>
</p>

<%= link_to 'Edit', edit_user_project_path(@user_project) %> |
<%= link_to 'Back', user_projects_path %>